# Generated by Django 4.2.16 on 2025-01-30 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Nazwa ćwiczenia"),
                ),
                ("description", models.TextField(verbose_name="Opis ćwiczenia")),
                (
                    "video",
                    models.FileField(
                        upload_to="exercise_videos/", verbose_name="Film instruktażowy"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=100)),
                ("weight_1", models.FloatField()),
                ("reps_1", models.PositiveIntegerField()),
                ("set_number", models.PositiveIntegerField(default=1)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "custom_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data wykonania"
                    ),
                ),
                (
                    "custom_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Godzina wykonania"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Nazwa planu")),
                (
                    "exercises",
                    models.ManyToManyField(
                        blank=True, related_name="training_plans", to="home.exercise"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "title")},
            },
        ),
    ]
